apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-template
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            limits:
              memory: 512Mi