apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-template-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-template

  minReplicas: 1
  maxReplicas: 2
  
  metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # (選用) 行為微調：避免擴縮容太過劇烈 (Flapping)
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120  # 縮容前觀察 2 分鐘，避免因為短暫低負載就縮容
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 30    # 擴容要快，不需要觀察窗
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15