apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      codeType: dotNet
      environment: stage

resources:
  - ../../base
replicas:
  - name: app-template
    count: 2
patches:
  - path: cpu-limit.yaml
  - path: ram-limit.yaml