apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-template
spec:
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  selector:
    matchLabels:
      name: app-template
  template:
    metadata:
      labels:
        name: app-template
    spec:
      containers:
        - name: app
          image: alpine:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          # livenessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          # readinessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
