apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-template-backend-config
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 86400  # 直接在這裡設定秒數
# 新增：自定義健康檢查
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 8080             # 確保對應到 Service 的 port