apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # 設定service account的存取權限不用設定secret
  # - path: image-pull-secrets.yaml
  - path: deployment-affinity.yaml
  - path: service.yaml
  #- path: backend-config.yaml